# Generated by Django 3.2.6 on 2021-08-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Employee Code')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('department', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
